@echo off
set BROWSER=none
echo Starting React server...
start /B "" "C:\Program Files\nodejs\npm.cmd" start
echo Waiting 20 seconds for server to boot...
timeout /t 20 /nobreak
echo Taking screenshots...
node screenshot.js
echo Killing node processes...
taskkill /F /IM node.exe /T
echo Finished!
